# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version=2.0.0
maven_group=dev.siliconcarbidecube
archives_name=create_redstone_additions
neoforge_archives_name=create-redstone-additions-neoforge
enabled_platforms=neoforge

# Minecraft properties
minecraft_version=1.21.1

# Dependencies
architectury_api_version=13.0.8
neoforge_version=21.1.217

# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Mod Dependencies
create_version=6.0.8-169
flywheel_version=1.0.6-beta-38
jei_version=19.27.0.336
ponder_version=1.0.69