architectury {
    common rootProject.enabled_platforms.split(',')
}

configurations {
    transformProductionNeoForge
}

artifacts {
    transformProductionNeoForge jar
}


repositories {
    maven { url = "https://maven.createmod.net/" }     // Ponder
    maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/" }

    // SpongePowered
    maven { url = "https://repo.spongepowered.org/maven" }
}

dependencies {

    modImplementation "dev.architectury:architectury:$rootProject.architectury_api_version"

    // Ponder (Common API)
    modCompileOnly("net.createmod.ponder:Ponder-Common-${minecraft_version}:${ponder_version}")

    // Mixins
    // annotationProcessor "org.spongepowered:mixin:0.8.5:processor"

}